export class Constants {
    appInfo = {
        phone: "+91 7896352435, +91 9999994253",
        email: "info@JogoSoft.com"
    }
    USERINFO = {
        ISLOGGEDIN: 'isLoggedIn'
    }
    STORAGE = {
        token: "token",
        theme: "skin-type",
        pinned: "pinned",
        currency: "currency",
        eventType: "eventType",
        id: 'id',
        plateform: 'plateform',
        showFilterDetails: 'showFilterDetails',
        second: 'seconds',
        NewtabHeaderRefresh: 'headerRefresh',
        searchEvent: 'searchEvent',
        betlistTable: 'betlisttable',
        betlistLiveTable: 'betlistLivetable',
        acceptAnyOdds: 'acceptAnyOdds',
        time: "date&time",
        marketTime: "marketdate&time",
        mktAccptAnyOdd: "mktAccptAnyOdd",
        privileges: "privileges",
        COIN: "jilicoin",
        COINSLIDER: "coinslider",
        LiveCasinoGameType: "liveCasinoType",
        SaveMarketFilter: "SaveMarketFilter",
        SaveMarketTypeFilter: "SaveMarketTypeFilter",
        USERINFO: "userInfoForRisk",
        showRoundOffStake:'showRoundOffStake',
        SaveMarketExpFilter: "SaveMarketExpFilter",
        liveBetListSchedular : 'liveBetListSchedular',
        NAVIGATETYPE:'navigateType',
        localStorageColumnMaintainvirsion : 'storageVirsion',
        clickToReloadButton:'clickToReloadButton',
        referCode:'referCode',
        trckUser:'trackUser',
        currencyRate:'currencyRate',
        isDemoUser:'isDemoUser',
        CURRENCYINFO:'curencyInfo',
        ACCESSKEY: "accesskey",
        CURRENCYCONV: "currencyconv",
        ISDISABLEBREDCRUMB:"isDisableBredcrumb",
        LANGUAGECHANGE:"languageChangeto",
        LiveCasinoProviderType: "liveCasinoProviderType",
        PLAYERPERMISSION:"playerprivilege"

    }
    THEME = {
        FIRST_SKIN: "skin-1",
        SECOND_SKIN: "skin-2",
        THIRD_SKIN: "skin-3",
    }
    ACTIONS = {
        EDIT: "edit",
        ADD: "add",
        DEL: "delete",
        UPDATE: "update"
    }
    BROADCASTKEY = {
        MENU: "menu",
        INVOKE_CHILDMENU: "invoke_child_menu_func",
        CHILDMENU: 'childMenu',
        SPECIALCHILDMENU: 'specialchildmenu',
        MANUALCHILDMENU: 'menualchildmenu',
        USERID: 'userId',
        BETSLIP: 'betslip',
        MOBILEBETSLIP: 'mobilebetslip',
        FANCYBETSLIP: 'fancyBetSlip',
        MOBILEFANCYBETSLIP: 'mobilefancyBetSlip',
        BETSLIPLIST: 'betsliplist',
        CHILDUSERID: 'childUserId',
        ACCOUNTSTATEMENT: 'accountStatement',
        ACCOUNTDETAILS: 'accountDetails',
        LOGIN: 'login',
        GETPLAYERINFO: 'getlogin',
        ADMINLOGIN: 'adminlogin',
        UPDATEONSAVE: 'updateOnSave',
        USERDETAILS: 'userDetails',
        PLAYEREVENTDETAIL: 'playerEventDetail',
        CHILDUSERDETAILS: 'childUserDetails',
        LIVEBETLIST: 'liveBetList',
        CURRENCY: 'currency',
        ISADDEDUSER: 'addedUser',
        SEARCHDATA: 'search',
        EVENTID: 'eventId',
        PINNED: 'pinned',
        NEwCURRENCY: 'newCurrency',
        GETFANCY: 'newfancy',
        ONLYFANCY: 'onlyFancy',
        ADMINMARKET: 'adminMarket',
        ADMINFANCY: 'adminFancy',
        GOTOPARENTNODE: 'gotoParentNode',
        SUBSCRIBEAGAIN: "subscribeagain",
        GETCAT: 'category',
        UPDATE: 'update',
        GETHI: 'gethi',
        PERSISTFORDOWNLOAD: 'getDatapdfExcelExport',
        CASINOBETSLIP: 'casinoBetSlip',
        GOTOHOME: 'gotoHome',
        FIREBASEEVENT: 'firebaseEvent',
        SEARCHEVENTS: 'searchevents',
        LIVETVEVENT: 'liveTvEvent',
        FORMMODAL: 'formModal',
        UPDATESIDEMENU: 'updateSideMenu',
        BETLISTLIVEAFTERVOIDBET: 'betlistLiveAfterVoid',
        BETSLIPOPEN: 'betSlipOpen',
        ACCESSMGMT: 'accessManagment',
        TRASHEDUSERS: 'trashedUsers',
        BLANKSCORECARD: 'scorecard',
        ACTIVEPLAYER: 'activePlayer',
        UPDATEVIEWBET: 'updateViewBet',
        NOTIFICATION: 'notification',
        RecentResult: 'recent-result',
        UpdateCurrecnyAftreSearch: 'update-currency',
        STAKEUPDATE: 'isStakeUpdate',
        updateSearchState: 'updateState',
        wicketMarket: 'wicketMarket',
        updateBankingLogs: 'updateBankingLogs',
        updateuserDetail: 'updateuserDetail',
        d3typeFilter: 'd3typeFilter',
        setFilter: 'setFilter',
        gameType: 'gameType',
        fantasy: 'fantasy',
        Updatefantasysidemenu: 'Updatefantasy',
        NOTIFICATIONDATA: 'notificationdata',
        CURRENCYREFLECT: 'currencyReflect',
        MATCHODDFIREBASE: 'matchoddfirebase',
        MOBILEOPENBETS: 'mobileOpenbets',
        // LOOSINGSTAKE : 'loosingStake',
        UPDATEODDSBETSLIP: 'updateOddsBetSlip',
        premiumMarket: 'premiumMarket',




    }
    ROLE = {
        PLAYER: "ROLE_PLAYER",
        ADMIN: "ROLE_ADMIN",
        SUP: "ROLE_SUPER_ADMIN",
        CANCREATE: "CAN_CREATE_MASTER",
        MASTER: "ROLE_MASTER",
        SUPMASTER: "ROLE_SUPER_MASTER",
        CANCREATEADMIN: "CAN_CREATE_ADMIN",
        WRITEPRIVILEGE: "WRITE_PRIVILEGE",
        GETROLE: '',
        FANCY: "ROLE_SUPER_ADMIN",
        OWNER: "ROLE_OWNER",
        TRADER: "ROLE_TRADER",
        TRMANAGER: "ROLE_TRMANAGER",
        TRCEATMANAGER: 'ROLE_CHEAT_MANAGER',
        CANADDMARKET: "CAN_ADD_MARKET",
        CANCREATEFACNY: "CAN_CREATE_FANCY",
        ASSOCIATE: 'ROLE_ASSOCIATE',
        Associate: "ASSOCIATE",
        CAN_EDIT_MARKET: 'CAN_EDIT_MARKET',
        CAN_CREATE_SUPER_ADMIN: 'CAN_CREATE_SUPER_ADMIN',
        CAN_CREATE_TRADER: 'CAN_CREATE_TRADER',
        CAN_ACCESS_CASINO_MGT: 'CAN_ACCESS_CASINO_MGT',
        CAN_ACCESS_ACCESS_MGT: 'CAN_ACCESS_ACCESS_MGT',
        CAN_CHANGE_ACC_STATUS: 'CAN_CHANGE_ACC_STATUS',
        CAN_UPDATE_PASSWORD: 'CAN_UPDATE_PASSWORD',
        MASTER_AGENT: 'MASTER_AGENT',
        BMANAGER: 'ROLE_BRAND_MANAGER'


    }
    PARAMSID = {
        userId: "userId=",
        eventId: "eventId=",
        mktId: "&marketId=",
        lastBetId: "lastBetId=",
        userParamId: 0,
        marketId: "marketId=",
        currency: "&currency=",
        selectionId: "selectionId=",
        gameType: 'gameType=',
        noOfBets: 'noOfBets=',
        viaUser: 'viaUser=',
        username: 'username=',
        isDeleted: 'isDeleted=',
        templateId: 'templateId=',
        userName: 'userName=',
        curency: "currency=",
        bannerIndex: "bannerIndex=",
        stake: 'stake=',
        eventTypeName: 'eventTypeName=',
        acceptTNC: 'acceptTNC=',
        userStatusFilter: 'userStatusFilter=',
        size: 'size=',
        pageNo: 'pageNo=',
        sourceType: 'sourceType=',
        suspend: 'suspend=',
        balance: 'balance=',
        gameid: 'gameid=',
        paymentId: 'paymentId=',
        ptRate: '&ptRate=',
        showOnRates: '&showOnRates=',
        returnUrl: 'returnUrl=',
        key: 'key=',
        id: 'id=',
        depositUrl: 'depositUrl=',
        deviceType: 'deviceType=',
        lang: 'lang=',
        isMobile: 'isMobile=',
        countryCode: 'countryCode=',
        sysUtr: 'sysUtr=',

    }
    STATUS = {
        ACTIVE: "Active",
        SUSPENDED: "Suspended",
        LOCKED: "Locked",
        FORBIDDEN: 'FORBIDDEN'
    }
    MKT_TABS = {
        nDepthData: 2,
        eventDepth: 1,
        parentDepth: 0,
        all: "all",
        today: "today",
        tomorrow: "tomorrow",
        inPlay: "inPlay",
        matchOdds: "matchOdds",
        Match_Odds: "Match_odds",
        fancy: "fancy",
        SEARCHSPORT: "searchsport",
        premium: "premium",
        bookmaker: 'Bookmaker 0% comm.',
        bookmaker2: 'Bookmaker Market',
        Bookmaker_Disc: 'Bookmaker_Disc',
        MATCH_ODDS: "MATCH_ODDS",
        OTHER_MKTS: "OTHER_MKTS",
        cricket: "cricket",
        soccer: "soccer",
        tennis: "tennis",
        pinned: "pinned",

    }
    BANKING = {
        FULLAMT: 'withdrawFullAmt'
    }

    IS_URL = {
        isUrl: 'betlive-list',
        isDownLine: 'down-line-list',
        trashUser: '/profile/trash-user'

    }
   
}
